apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-service-monitor
  labels:
    project: python
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: python
  namespaceSelector:
    any: true
  endpoints:
  - port: api
    interval: 30s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: python-alert
spec:
  groups:
  - name: python-alerts
    rules:
    - alert: HighRequestRate  
      expr: rate(info_requests_total[1m]) * 60 > 5  
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Wysoki wskaźnik żądań"
        description: "Metryka info_requests_created generuje więcej niż 5 żądań na minutę."