prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false

kubeEtcd:
  service:
    targetPort: 2381

global:
  rbac:
    createAggregateClusterRoles: true