apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls
spec:
  secretName: app-tls          # cert-manager utworzy ten Secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - python.<GATEWAY-IP>.nip.io   # ZMIEŃ — publiczny IP Gatewaya (patrz README, krok 4)
  duration: 2160h               # 90 dni
  renewBefore: 360h             # odnowienie 15 dni przed wygaśnięciem
